import { Badge, EmptyState, KeyValue, Panel } from '../../components/ui';
import { EvidenceTabs, SceneFields, sceneText, structuralRows, type SceneProps } from './parts';

export default function RunScene({ scene, onAction }: SceneProps) {
  const t = sceneText(scene);
  if (scene.kind === 'trace') return <Panel title="Trace waterfall"><div className="panel-pad" data-scene-template="trace"><div className="trace-axis"><span>Start</span><span>Elapsed time</span><span>End</span></div>{__ATLAS_REVIEW__ ? <ol className="trace-spans">{scene.rows.map((r, i) => <li key={i}><span className="caption break">{r.label}</span><div className="trace-bar" style={{ marginInlineStart: `${i * 8}%`, width: `${64 - i * 6}%` }}><Badge>{r.status}</Badge></div><span className="caption break">{r.detail}</span></li>)}</ol> : <EmptyState icon="activity" headingLevel={3} title="No spans received">Not observed — durations, clock skew and sampling come from scoped telemetry.</EmptyState>}</div></Panel>;
  if (scene.kind === 'observer') return <div className="stack-16" data-scene-template="observer"><div className="metrics">{['Coverage', 'Freshness', 'Latency', 'Source health'].map(k => <section className="panel panel-pad stack" key={k}><h2 className="label">{k}</h2><span className="metric-value">Not observed</span></section>)}</div><SceneFields scene={scene} /><EvidenceTabs scene={scene} onAction={onAction} /></div>;
  return <div className="stack-16" data-scene-template="run"><Panel title="Run identity"><div className="panel-pad"><KeyValue items={[['State', <Badge key="state">{t.state}</Badge>], ['Task', __ATLAS_REVIEW__ ? t.entity : 'Not observed'], ['Attempt', 'Not observed'], ['Lease', 'Not observed']]} /></div></Panel><Panel title="Execution timeline"><ol className="run-timeline">{['Admission', 'Lease', 'Execute', 'Artifacts', 'Cleanup'].map(k => <li key={k}><span className="timeline-dot" aria-hidden="true" /><div className="stack"><strong className="label">{k}</strong><span className="caption">Not observed — awaiting authoritative evidence</span></div></li>)}</ol>{__ATLAS_REVIEW__ && structuralRows(scene).length > 0 && <div className="panel-pad caption">Illustrative state: {t.state}</div>}</Panel><SceneFields scene={scene} /><EvidenceTabs scene={scene} onAction={onAction} /></div>;
}
