import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router';
import { useApp, capability, app } from '../../data/app-store';
import { actionGate, loadCollection, type ServiceAction, type ServiceRecord } from '../../data/service';
import { getAll, type DefinitionRecord } from '../../lib/storage';
import { useDeviceQuery } from '../../lib/hooks';
import { Badge, Banner, Button, ButtonLink, EmptyState, KeyValue, Panel } from '../../components/ui';
import { Tabs } from '../../components/overlays';
import { CommandDialog } from './ServiceModulePage';
import { DOMAIN_STATES, statePresentation } from '../../data/states';

export function OnboardingPanel({ record }: { record?: ServiceRecord|null }) {
  const session=useApp(s=>s.session);const grant=capability('org:create');
  return <Panel title="Organization setup & readiness"><div className="panel-pad"><div className="archive-readiness">{[
    ['Organization & workspace','/tenancy','organization_ready'],['Connect your repository','/code','repository_ready'],['Configure AI access & budget','/gateway','gateway_ready'],['Invite your team','/identity','membership_ready'],
  ].map(([label,to,key])=><div className="card stack-12" key={key}><strong className="label">{label}</strong><Badge>{typeof record?.fields?.[key]==='boolean'?(record.fields[key]?'Observed':'Incomplete'):'Not observed'}</Badge><ButtonLink to={to}>Inspect readiness</ButtonLink></div>)}</div><div className="row" style={{marginTop:16}}><ButtonLink to="/definitions/organization">Organization draft</ButtonLink><Button blocked={grant.ok?'Select an organization resource with an offered create action.':grant.reason}>Create organization</Button></div><p className="caption">{session?'Readiness must match the current organization and project revision.':'Local organization drafts do not create a service tenant.'}</p></div></Panel>;
}
export function MembershipPanel({ record }: {record:ServiceRecord|null}) {
  const session=useApp(s=>s.session);
  return <Panel title="Membership, invitations & effective access"><div className="panel-pad stack-16"><div className="archive-readiness">{['Members','Pending invitations','Role policies','Active sessions'].map(k=><div className="card stack-8" key={k}><strong className="caption">{k}</strong><strong>{typeof record?.fields?.[k.toLowerCase().replaceAll(' ','_')]==='number'?String(record.fields[k.toLowerCase().replaceAll(' ','_')]):'Not observed'}</strong></div>)}</div><KeyValue items={([['Organization','org'],['Workspace','workspace'],['Project','project']] as const).map(([label,key])=>[label,session?.scope[key]??'Not observed'])}/><div className="row"><ButtonLink to="/definitions/member-invitation">Invitation draft</ButtonLink><ButtonLink to="/definitions/role-policy">Role policies</ButtonLink><ButtonLink to="/states/IAM-Scope">Session recovery</ButtonLink></div><p className="caption">Effective permissions come from grants in the current scope. Role names describe templates and never authorize a command.</p></div></Panel>;
}
export function HubPanel() {
  return <Panel title="Workspace resource inheritance"><div className="panel-pad stack-16"><nav className="archive-readiness" aria-label="Resource hub">{[['MCP servers','mcp-resource'],['Skills','skill-resource'],['Rules','rule-resource'],['Plugins','plugin-resource'],['Hooks','hook-resource'],['Sidecars','sidecar-resource']].map(([label,id])=><Link className="card stack-8" to={`/resources/drafts/${id}`} key={id}><strong>{label}</strong><span className="caption">Inspect version pins & consumers</span></Link>)}</nav><p className="caption">Projects compose pinned resources into agent definitions. Required workspace rules retain their scope; compatible version upgrades require an explicit selection.</p><ButtonLink to="/agents">Compose an agent</ButtonLink></div></Panel>;
}
export function MemoryPanel() {
  const {data:records}=useDeviceQuery(()=>getAll<DefinitionRecord>('definitions','schemaId','memory'),[],[] as DefinitionRecord[]);const [query,setQuery]=useState('');const [tab,setTab]=useState('knowledge');
  const live=records.filter(r=>!r.archived);const match=live.filter(r=>`${r.name} ${r.data.knowledge_type??r.data.layer??''}`.toLowerCase().includes(query.toLowerCase())&&(tab!=='review'||String(r.data.knowledge_type??r.data.layer??'').toLowerCase().includes('episodic')));
  const table=<div className="panel-pad stack-16"><label className="field-label" htmlFor="knowledge-search">Search knowledge drafts</label><input id="knowledge-search" className="input" type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name or knowledge type"/><div className="table-wrap"><table className="table"><caption className="sr-only">Device knowledge drafts</caption><thead><tr>{['Knowledge item','Knowledge type','Revision','Authority','Action'].map(k=><th scope="col" key={k}>{k}</th>)}</tr></thead><tbody>{match.length?match.map(r=><tr key={r.id}><th scope="row">{r.name}</th><td>{String(r.data.knowledge_type??r.data.layer??'Not observed')}</td><td>{r.rev}</td><td><Badge>Device draft</Badge></td><td><ButtonLink to={`/memory/drafts/memory/${r.id}`}>Read & edit</ButtonLink></td></tr>):<tr><td colSpan={5}><EmptyState title={query?'No matching knowledge drafts':'No knowledge drafts'} headingLevel={3}>Save a local draft or connect a service to inspect verified knowledge.</EmptyState></td></tr>}</tbody></table></div><p className="caption">{match.length} device drafts displayed. Publication, verification and promotion are independent service outcomes.</p></div>;
  return <Panel title="Workspace memory layers"><div className="panel-pad archive-readiness">{[['Working memory','Ephemeral per attempt'],['Structural graph','Repository AST lineage'],['Episodic records','Draft → review → promote'],['Semantic knowledge','Policies and domain rules']].map(([label,note])=><div className="card stack-8" key={label}><strong>{label}</strong><Badge>Not observed</Badge><span className="caption">{note}</span></div>)}</div><Tabs label="Memory bank" value={tab} onValueChange={setTab} tabs={[{id:'knowledge',label:'Knowledge',content:table},{id:'review',label:'Review queue',content:table},{id:'settings',label:'Engine settings',content:<div className="panel-pad"><ButtonLink to="/memory/drafts/memory-policy">Inspect memory policy</ButtonLink></div>},{id:'import',label:'Import',content:<div className="panel-pad"><ButtonLink to="/definitions/memory">Import a device definition</ButtonLink><p className="caption">Importing a draft does not ingest repository knowledge into a service.</p></div>}]} /><div className="panel-pad"><ButtonLink to="/states/MM-Context">Inspect lineage & context budget</ButtonLink></div></Panel>;
}
export function ProposedPlans() {
  const session=useApp(s=>s.session);const [records,setRecords]=useState<ServiceRecord[]>([]);const [selected,setSelected]=useState<string|null>(null);const [error,setError]=useState<string|null>(null);const [pending,setPending]=useState<ServiceAction|null>(null);
  const refresh=useCallback(async()=>{if(!session)return;try{const c=await loadCollection('workflow');if(app.get().session===session){setRecords(c.items.filter(r=>(DOMAIN_STATES.TaskDAG as readonly string[]).includes(r.status)));setError(null);}}catch(e){if(app.get().session===session)setError((e as Error).message);}},[session]);
  useEffect(()=>{setRecords([]);setSelected(null);setPending(null);setError(null);if(session)void refresh();},[session,refresh]);
  const record=records.find(r=>r.id===selected)??null;const action=record?.actions?.find(a=>a.grant==='dag:plan_approve'&&a.label==='Approve plan');
  return <Panel title="Plan-first · service proposals"><div className="panel-pad stack-16"><div className="row">{DOMAIN_STATES.TaskDAG.map(s=><Badge key={s}>{statePresentation(s).label}</Badge>)}</div>{error&&<Banner tone="warning" title="Proposed plans unavailable">{error}</Banner>}<div className="table-wrap"><table className="table"><caption className="sr-only">Proposed DAG plans</caption><thead><tr>{['Plan','Immutable input package','State','Revision','Human checkpoints'].map(k=><th scope="col" key={k}>{k}</th>)}</tr></thead><tbody>{records.length?records.map(r=><tr key={r.id}><th scope="row"><button className="link-button" aria-pressed={selected===r.id} onClick={()=>setSelected(r.id)}>{r.name}</button></th><td className="break">{String(r.fields?.input_package??'Not observed')}</td><td><Badge>{statePresentation(r.status).label}</Badge></td><td>{r.revision}</td><td>{String(r.fields?.human_checkpoints??'Not observed')}</td></tr>):<tr><td colSpan={5}><EmptyState title="No authorized plans loaded" headingLevel={3}>Submit a frozen specification to AI, inspect memory preparation, then review the offered plan.</EmptyState></td></tr>}</tbody></table></div><Button onClick={()=>action&&setPending(action)} blocked={actionGate(record,action)??undefined}>Approve plan</Button><div className="row"><ButtonLink to="/memory">Memory preparation</ButtonLink><ButtonLink to="/states/WF-Task">Task inspector & immutable inputs</ButtonLink><ButtonLink to="/execution">Human checkpoint</ButtonLink></div></div>{pending&&record&&<CommandDialog module="workflow" record={record} action={pending} onClose={()=>setPending(null)} onDone={refresh}/>}</Panel>;
}
