#!/usr/bin/env node
// Generates deploy/staging-worker.js: a Worker that serves exactly the files of one committed release (release/<channel>
// at an immutable commit), verifies each file's SHA-256 before serving or caching it, adds the security headers and serves
// index.html for client routes. Usage: node tools/staging-worker.mjs <artifact-commit-sha> [channel]
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const [sha, channel = 'staging'] = process.argv.slice(2);
if (!/^[0-9a-f]{40}$/.test(sha || '')) throw new Error('Pass the full 40-character commit SHA that contains the release.');
const root = new URL('..', import.meta.url).pathname;
const m = JSON.parse(readFileSync(join(root, 'release', channel, 'release-manifest.json'), 'utf8'));
const files = Object.fromEntries(Object.entries(m.files).map(([p, f]) => [p, f.sha256]));
const origin = `https://raw.githubusercontent.com/ldqanh1408/hehe/${sha}/frontend/atlas-web/release/${channel}`;
const headersFile = readFileSync(join(root, 'public', '_headers'), 'utf8');
const security = Object.fromEntries(headersFile.split('\n/assets/*')[0].split('\n').filter((l) => /^\s+\S+:/.test(l)).map((l) => { const i = l.indexOf(':'); return [l.slice(0, i).trim(), l.slice(i + 1).trim()]; }));

const src = `// Generated by tools/staging-worker.mjs — do not edit. Release ${m.buildId} (${m.fileCount} files), artifact commit ${sha}.
const ORIGIN = ${JSON.stringify(origin)};
const RELEASE = ${JSON.stringify(m.buildId)};
const FILES = ${JSON.stringify(files)};
const SECURITY = ${JSON.stringify({ ...security, 'X-Robots-Tag': 'noindex, nofollow' })};
const TYPES = { html: 'text/html; charset=utf-8', js: 'text/javascript; charset=utf-8', css: 'text/css; charset=utf-8', json: 'application/json; charset=utf-8', svg: 'image/svg+xml', woff2: 'font/woff2', woff: 'font/woff', txt: 'text/plain; charset=utf-8', ico: 'image/x-icon', png: 'image/png' };

async function sha256(buf) {
  const d = await crypto.subtle.digest('SHA-256', buf);
  return [...new Uint8Array(d)].map((b) => b.toString(16).padStart(2, '0')).join('');
}

async function load(path, ctx) {
  const want = FILES[path];
  const key = new Request('https://atlas-release.cache/' + want);
  const cache = caches.default;
  const hit = await cache.match(key);
  if (hit) return hit.arrayBuffer();
  const up = await fetch(ORIGIN + path, { cf: { cacheTtl: 86400, cacheEverything: true } });
  if (!up.ok) throw new Error('upstream ' + up.status);
  const buf = await up.arrayBuffer();
  if ((await sha256(buf)) !== want) throw new Error('integrity mismatch for ' + path);
  ctx.waitUntil(cache.put(key, new Response(buf, { headers: { 'Cache-Control': 'public, max-age=31536000, immutable' } })));
  return buf;
}

export default {
  async fetch(request, env, ctx) {
    if (request.method !== 'GET' && request.method !== 'HEAD') return new Response('Method not allowed', { status: 405, headers: { Allow: 'GET, HEAD', ...SECURITY } });
    const url = new URL(request.url);
    let path;
    try { path = decodeURIComponent(url.pathname); } catch { return new Response('Bad request', { status: 400, headers: SECURITY }); }
    if (path.includes('..') || path.includes('\\\\')) return new Response('Bad request', { status: 400, headers: SECURITY });
    if (!FILES[path]) {
      // Client-side routes get the app shell; anything that looks like a file and is not in the release is a real 404.
      if (/\\.[a-z0-9]+$/i.test(path) || path.startsWith('/assets/')) return new Response('Not found', { status: 404, headers: { 'Content-Type': 'text/plain; charset=utf-8', 'Cache-Control': 'no-store', ...SECURITY } });
      path = '/index.html';
    }
    const etag = '"' + FILES[path] + '"';
    const ext = path.split('.').pop().toLowerCase();
    const headers = { 'Content-Type': TYPES[ext] || 'application/octet-stream', ETag: etag, 'X-Atlas-Release': RELEASE, ...SECURITY,
      'Cache-Control': path.startsWith('/assets/') ? 'public, max-age=31536000, immutable' : 'no-cache' };
    if (request.headers.get('If-None-Match') === etag) return new Response(null, { status: 304, headers });
    let body;
    try { body = await load(path, ctx); }
    catch (e) { return new Response('Release file unavailable: ' + e.message, { status: 502, headers: { 'Content-Type': 'text/plain; charset=utf-8', 'Cache-Control': 'no-store', ...SECURITY } }); }
    return new Response(request.method === 'HEAD' ? null : body, { status: 200, headers });
  },
};
`;
writeFileSync(join(root, 'deploy', 'staging-worker.js'), src);
console.log(`deploy/staging-worker.js: ${Object.keys(files).length} files, ${src.length} bytes, release ${m.buildId}`);
